name: Test via pytest

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out release tag
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'
